services:


  misp:


    image: coolacid/misp


    container_name: misp


    restart: unless-stopped


    ports:
      - "8080:80"
      - "8443:443"


    volumes:
      - misp-data:/var/www/MISP


    environment:
      - TZ=Europe/Madrid



volumes:
  misp-data:


